export const AUDIT_ACTIONS = {
  PROCESS_CREATED: "PROCESS_CREATED",
  PROCESS_UPDATED: "PROCESS_UPDATED",
  PROCESS_SOFT_DELETED: "PROCESS_SOFT_DELETED",
  PROCESS_RESTORED: "PROCESS_RESTORED",
  PROCESS_VIEWED: "PROCESS_VIEWED",
  PROCESS_DOCUMENTS_VIEWED: "PROCESS_DOCUMENTS_VIEWED",
  PROCESS_MOVIMENTACOES_VIEWED: "PROCESS_MOVIMENTACOES_VIEWED",
  PROCESS_EVENTOS_VIEWED: "PROCESS_EVENTOS_VIEWED",
  DOCUMENT_VIEWED: "DOCUMENT_VIEWED",
  FINANCE_SENSITIVE_VIEWED: "FINANCE_SENSITIVE_VIEWED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_REJECTED: "LOGIN_REJECTED",
  WEBHOOK_RECEIVED: "WEBHOOK_RECEIVED",
  WEBHOOK_PROCESSED: "WEBHOOK_PROCESSED",
  CRON_STARTED: "CRON_STARTED",
  CRON_COMPLETED: "CRON_COMPLETED",
  CRON_FAILED: "CRON_FAILED",
  AUDIT_EXPORT_REQUESTED: "AUDIT_EXPORT_REQUESTED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
